import tkinter
main_window=tkinter.Tk()
main_window.title('MyApp')
label1=tkinter.Label(main_window,width=20, text='Login',bg='white')
label1.pack()
label2=tkinter.Label(main_window,width=15, text='Username',bg='Gray')
label2.pack()
label2=tkinter.Entry(main_window)
label2.pack()
label3=tkinter.Label(main_window,width=15, text='Password',bg='Gray')
label3.pack()
label3=tkinter.Entry(main_window)
label3.pack()
label4=tkinter.Label(main_window,width=20, text='Sign in',bg='blue')
label4.pack()
label5=tkinter.Label(main_window,width=20, text='Forgot your password?',bg='white')
label5.pack()
main_window.mainloop()